### ISSUE TITLE
Install fresh environment not working (at least 1.2107.3+) htpasswd issue on Init.

### ISSUE THREAD

**Issue by jcit1** [place-labs/partner-environment#57]
Installing partner environment fresh on a new laptop or for a new developer there is a problem when ./placeos start is run.  Htpasswd issue happens that stops installation.

PlaceOS: 1.2107.3+ (could be earlier)

**To Reproduce**
Install fresh (delete all volumes/containers)

**Expected behavior**
./PlaceOs start to work and system to run.

**Screenshots**
If applicable, add screenshots to help explain you see.

![a6babdc2-6faf-45fe-bf52-a3b1156ac036](https://user-images.githubusercontent.com/10040568/128947119-a9624711-86d4-42db-9b33-3d87e5bf2143.jpg)
![b5345e61-23a5-4eda-9341-e8fc802f4c8c](https://user-images.githubusercontent.com/10040568/128947135-dd585745-4d99-43f6-a6c8-6fad2467a199.jpg)

**Comment by caspiano** [comment]
Thanks for the clear report @jcit1, this should be resolved with the latest commits on master.

**Comment by kimburgess** [comment]
Just observing this one in action - re-opening while investigated.

**Comment by kimburgess** [comment]
Cause of this issue is the [`generate-secrets` task in `init`](https://github.com/PlaceOS/init/blob/87b8850e5f669166755a49736e5c60259e818067/scripts/generate-secrets#L57). Is expecting `$PLACE_EMAIL` and `$PLACE_PASSWORD` env vars to be available. These read from `.env`, but [no longer appear to be set there](https://github.com/place-labs/partner-environment/blob/d065355303ed951383cac378d4eb5b49be2ea26e/.env#L31-L33).

**Comment by caspiano** [comment]
Resolved by https://github.com/place-labs/partner-environment/issues/57

**Comment by kimburgess** [comment]
@caspiano that's a slightly recursive closure there.

Issues remain with creation of `.htpasswd-kibana` based on current state in 80619d4.

**Comment by caspiano** [comment]
I can't reproduce, @viv-4 reported fixed after #66

**Comment by kimburgess** [comment]
Cause found - the env this was impacting had a `.htpasswd-kibana` _directory_ as a residual from https://github.com/place-labs/partner-environment/pull/63.

Is it possible to catch and either auto-resolve, or warn if this is encountered?
